name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  iOS-11:
    runs-on: macOS-latest
    strategy:
          matrix:
            destination: ['platform=iOS Simulator,OS=11.0,name=iPhone 8']
            xcode: ['/Applications/Xcode_12.app/Contents/Developer']
    steps:
    - uses: actions/checkout@v1
      
    - name: Switch to Xcode 12
      run: sudo xcode-select --switch /Applications/Xcode_12.app
      
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
      
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 8' -scheme 'UIPorter-Package'
  iOS-12:
    runs-on: macOS-latest
    strategy:
          matrix:
            destination: ['platform=iOS Simulator,OS=12.0,name=iPhone 8']
            xcode: ['/Applications/Xcode_12.app/Contents/Developer']
    steps:
    - uses: actions/checkout@v1
      
    - name: Switch to Xcode 12
      run: sudo xcode-select --switch /Applications/Xcode_12.app
      
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
      
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 8' -scheme 'UIPorter-Package'
  iOS-13:
    runs-on: macOS-latest
    strategy:
          matrix:
            destination: ['platform=iOS Simulator,OS=13.0,name=iPhone 8']
            xcode: ['/Applications/Xcode_12.app/Contents/Developer']
    steps:
    - uses: actions/checkout@v1
      
    - name: Switch to Xcode 12
      run: sudo xcode-select --switch /Applications/Xcode_12.app
      
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
      
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 8' -scheme 'UIPorter-Package'
  iOS-14:
    runs-on: macOS-latest
    strategy:
          matrix:
            destination: ['platform=iOS Simulator,OS=14.0,name=iPhone 8']
            xcode: ['/Applications/Xcode_12.app/Contents/Developer']
    steps:
    - uses: actions/checkout@v1
      
    - name: Switch to Xcode 12
      run: sudo xcode-select --switch /Applications/Xcode_12.app
      
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
      
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 8' -scheme 'UIPorter-Package'
    
  macOS-10_10:
    runs-on: macOS-10.10
    strategy:
          matrix:
            destination: ['platform=iOS Simulator,OS=11.0,name=iPhone 8']
            xcode: ['/Applications/Xcode_12.app/Contents/Developer']
    steps:
    - uses: actions/checkout@v1
      
    - name: Switch to Xcode 12
      run: sudo xcode-select --switch /Applications/Xcode_12.app
      
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
      
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 8' -scheme 'UIPorter-Package'
